### ISSUE TITLE
Start - Client Only Middleware Causes H3Error

### ISSUE THREAD

**Issue by scrawfor** [tannerlinsley/react-location#2874]
### Which project does this relate to?

Start

### Describe the bug

Creating client only middleware for server functions results in the following error:

```
[h3] [unhandled] H3Error: createMiddleware must be called with a "use" property!
    at Object.handleCreateMiddlewareCallExpression (file:///home/projects/tanstack-router-9lnxdn/node_modules/@tanstack/start-vite-plugin/dist/esm/compilers.js:271:11)
    at eval (file:///home/projects/tanstack-router-9lnxdn/node_modules/@tanstack/start-vite-plugin/dist/esm/compilers.js:124:40)
    at eval (file:///home/projects/tanstack-router-9lnxdn/node_modules/@tanstack/start-vite-plugin/dist/esm/compilers.js:123:44)
    at enter (file:///home/projects/tanstack-router-9lnxdn/node_modules/@tanstack/start-vite-plugin/dist/esm/compilers.js:122:24)
    at NodePath._call (/home/projects/tanstack-router-9lnxdn/node_modules/@babel/traverse/lib/path/context.js:49:20)
    at NodePath.call (/home/projects/tanstack-router-9lnxdn/node_modules/@babel/traverse/lib/path/context.js:39:18)
    at NodePath.visit (/home/projects/tanstack-router-9lnxdn/node_modules/@babel/traverse/lib/path/context.js:88:31)
    at TraversalContext.visitQueue (/home/projects/tanstack-router-9lnxdn/node_modules/@babel/traverse/lib/context.js:90:16)Caused by: Error: createMiddleware must be called with a "use" property!
```

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-9lnxdn?file=app%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

Create a client only Middleware

```ts
const middleware = createMiddleware().client(async ({ next }) => {
  console.log('Client Middlware');
  return next();
});
```

### Expected behavior

Middleware would work as expected

### Platform

- OS: macOS
- Browser: Chrome / Firefox
- Version: Latest

**Comment by keuller-emma** [comment]
hey @scrawfor, if I understand correctly you're trying to create a client middleware for a server function. By design Server functions will run on the server, which means you should create a server middleware rather than a client one.

```ts
const middleware = createMiddleware().server(async ({ next }) => {
  console.log("Server Middleware: ");
  return next();
});
```

I'm not an expert on TanStack Start, and my assumption may be wrong. I replaced your client middleware with the server one and it works. Did you try that?

**Comment by scrawfor** [comment]
> hey @scrawfor, if I understand correctly you're trying to create a client middleware for a server function. By design Server functions will run on the server, which means you should create a server middleware rather than a client one.
> 
> ```ts
> const middleware = createMiddleware().server(async ({ next }) => {
>   console.log("Server Middleware: ");
>   return next();
> });
> ```
> 
> I'm not an expert on TanStack Start, and my assumption may be wrong. I replaced your client middleware with the server one and it works. Did you try that?

server functions have both client and server middleware. 

https://tanstack.com/router/latest/docs/framework/react/start/middleware

**Comment by brenelz** [comment]
Looks like there was a pr that mentioned this. Is this fixed?
